export const SET_STRUCTURE = "SET_STRUCTURE";
export const SET_EQUIPMENT = "SET_EQUIPMENT";
export const ADD_EQUIPMENT = "ADD_EQUIPMENT";
export const DELETE_EQUIPMENT = "DELETE_EQUIPMENT";
export const EDIT_EQUIPMENT = "EDIT_EQUIPMENT";
export const SHOW_EQUIPMENT = "SHOW_EQUIPMENT";
